# Generated by Django 4.0.6 on 2022-07-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=255)),
                ('pUrl', models.CharField(max_length=500)),
                ('pImage', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
    ]
